#ifndef DEF_EIGEN_H
#define DEF_EIGEN_H


#define EIGEN_PKOPF             "Werkstueck"
#define EIGEN_PKOPF_NAME        "Wst_Name"
#define EIGEN_PKOPF_L           "Wst_Laenge"
#define EIGEN_PKOPF_B           "Wst_Breite"
#define EIGEN_PKOPF_D           "Wst_Dicke"
#define EIGEN_PKOPF_KANTE_VO    "Wst_Kante_vo"
#define EIGEN_PKOPF_KANTE_HI    "Wst_Kante_hi"
#define EIGEN_PKOPF_KANTE_LI    "Wst_Kante_li"
#define EIGEN_PKOPF_KANTE_RE    "Wst_Kante_re"
#define EIGEN_PKOPF_GUTSEI      "Wst_GutSei"
#define EIGEN_PKOPF_GUTSEI_OBEN "gut oben"
#define EIGEN_PKOPF_GUTSEI_UNTEN "gut unten"

#define EIGEN_BOHR              "Bohrung"
#define EIGEN_BOHR_BEZUG        "Bezug"
#define EIGEN_BOHR_DM           "BO_dm"
#define EIGEN_BOHR_TI           "BO_ti"
#define EIGEN_BOHR_X            "BO_pos_x"
#define EIGEN_BOHR_Y            "BO_pos_y"
#define EIGEN_BOHR_Z            "BO_pos_z"
#define EIGEN_BOHR_AFB          "BO_afb"
#define EIGEN_BOHR_ZSM          "BO_zsm"
#define EIGEN_BOHR_WKZ          "BO_wkz"

#define EIGEN_RTA               "Rechtecktasche"
#define EIGEN_RTA_BEZUG         "Bezug"
#define EIGEN_RTA_LA            "RTA_la"
#define EIGEN_RTA_BR            "RTA_br"
#define EIGEN_RTA_TI            "RTA_ti"
#define EIGEN_RTA_X             "RTA_pos_x"
#define EIGEN_RTA_Y             "RTA_pos_y"
#define EIGEN_RTA_Z             "RTA_pos_z"
#define EIGEN_RTA_DREWI         "RTA_drewi"
#define EIGEN_RTA_RAD           "RTA_rad"
#define EIGEN_RTA_AUSR          "RTA_ausr"
#define EIGEN_RTA_AFB           "RTA_afb"
#define EIGEN_RTA_ZSM           "RTA_zsm"
#define EIGEN_RTA_WKZ           "RTA_wkz"

#define EIGEN_NUT               "Nutbearbeitung"
#define EIGEN_NUT_BEZUG         "Bezug"
#define EIGEN_NUT_XS            "NUT_xs"
#define EIGEN_NUT_YS            "NUT_ys"
#define EIGEN_NUT_ZS            "NUT_zs"
#define EIGEN_NUT_XE            "NUT_xe"
#define EIGEN_NUT_YE            "NUT_ye"
#define EIGEN_NUT_ZE            "NUT_ze"
#define EIGEN_NUT_TI            "NUT_ti"
#define EIGEN_NUT_BR            "NUT_br"
#define EIGEN_NUT_AFB           "NUT_afb"

#define EIGEN_FAUFRUF           "Fraeser-Aufruf"
#define EIGEN_FAUFRUF_BEZUG     "Bezug"
#define EIGEN_FAUFRUF_X         "FA_pos_x"
#define EIGEN_FAUFRUF_Y         "FA_pos_y"
#define EIGEN_FAUFRUF_Z         "FA_pos_z"
#define EIGEN_FAUFRUF_TI        "FA_ti"
#define EIGEN_FAUFRUF_RADKOR    "FA_radkor"
#define EIGEN_FAUFRUF_WKZ       "FA_wkz"
#define EIGEN_FAUFRUF_AFB       "FA_afb"
#define EIGEN_FAUFRUF_ANTYP     "FA_antyp"
#define EIGEN_FAUFRUF_ABTYP     "FA_abtyp"
#define EIGEN_FAUFRUF_ANWEG     "FA_anweg"
#define EIGEN_FAUFRUF_ABWEG     "FA_abweg"

#define EIGEN_FGERADE           "Gerade fraesen"
#define EIGEN_FGERADE_BEZUG     "Bezug"
#define EIGEN_FGERADE_XS        "FG_xs"
#define EIGEN_FGERADE_YS        "FG_ys"
#define EIGEN_FGERADE_ZS        "FG_zs"
#define EIGEN_FGERADE_XE        "FG_xe"
#define EIGEN_FGERADE_YE        "FG_ye"
#define EIGEN_FGERADE_ZE        "FG_ze"
#define EIGEN_FGERADE_AFB       "FG_afb"
#define EIGEN_FGERADE_TISTA     "FG_tiSta"
#define EIGEN_FGERADE_TIEND     "FG_tiEnd"

#define EIGEN_FBOGEN            "Bogen fraesen"
#define EIGEN_FBOGEN_BEZUG      "Bezug"
#define EIGEN_FBOGEN_XS         "FB_xs"
#define EIGEN_FBOGEN_YS         "FB_ys"
#define EIGEN_FBOGEN_ZS         "FB_zs"
#define EIGEN_FBOGEN_XE         "FB_xe"
#define EIGEN_FBOGEN_YE         "FB_ye"
#define EIGEN_FBOGEN_ZE         "FB_ze"
#define EIGEN_FBOGEN_RAD        "FB_rad"
#define EIGEN_FBOGEN_UZS        "FB_uzs"
#define EIGEN_FBOGEN_AFB        "FB_afb"
#define EIGEN_FBOGEN_TISTA      "FB_tiSta"
#define EIGEN_FBOGEN_TIEND      "FB_tiEnd"

#define EIGEN_GEHRUNG           "Gehrung"
#define EIGEN_GEHRUNG_BEZUG     "Bezug"
#define EIGEN_GEHRUNG_XS        "GEHR_xs"
#define EIGEN_GEHRUNG_YS        "GEHR_ys"
#define EIGEN_GEHRUNG_XE        "GEHR_xe"
#define EIGEN_GEHRUNG_YE        "GEHR_ye"
#define EIGEN_GEHRUNG_WI        "GEHR_wi"
#define EIGEN_GEHRUNG_AFB       "GEHR_afb"
#define EIGEN_GEHRUNG_WKZ       "GEHR_wkz"
#define EIGEN_GEHRUNG_RITI      "GEHR_riti"
#define EIGEN_GEHRUNG_STI       "GEHR_sti"





#endif // DEF_EIGEN_H
